server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/user/**
        - id: activity-service
          uri: lb://activity-service
          predicates:
            - Path=/api/activity/**
        - id: match-service
          uri: lb://match-service
          predicates:
            - Path=/api/match/**
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/payment/**
        - id: message-service
          uri: lb://message-service
          predicates:
            - Path=/api/message/**
        - id: review-service
          uri: lb://review-service
          predicates:
            - Path=/api/review/**
