server:
  port: 8003

spring:
  application:
    name: match-service
  
  redis:
    host: localhost
    port: 6379
    database: 2
  
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

logging:
  level:
    com.dazi.match: DEBUG
